### ISSUE TITLE
vDistance not loading

### ISSUE THREAD

**Issue by LadyHaley** [chrisgdt/MythicMobsExtension#2]
Im not sure if its any other conditions or mechanics either since I dont use much from MME but I cant get this working

```
[13:34:11] [Server thread/WARN]: [MythicMobs] ✗ Configuration Error in Condition CustomCondition
[13:34:11] [Server thread/WARN]: [MythicMobs] --| File: Unknown
[13:34:11] [Server thread/WARN]: [MythicMobs] --| Error Message: Failed to load custom condition vdistance
[13:34:11] [Server thread/WARN]: [MythicMobs] --| Mechanic Line: vdistance{d=2to20;action=true}
[13:34:11] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[13:34:11] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
[13:34:11] [Server thread/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
[13:34:11] [Server thread/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
[13:34:11] [Server thread/WARN]: 	at MythicMobsExtension-MC-1.21.1-v1.757-SNAPSHOT.jar//com.gmail.berndivader.mythicmobsext.conditions.CustomConditions.registerCondition(CustomConditions.java:41)
[13:34:11] [Server thread/WARN]: 	at MythicMobsExtension-MC-1.21.1-v1.757-SNAPSHOT.jar//com.gmail.berndivader.mythicmobsext.conditions.CustomConditions.onMythicMobsConditionsLoadEvent1(CustomConditions.java:26)
[13:34:11] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1769.execute(Unknown Source)
[13:34:11] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[13:34:11] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[13:34:11] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[13:34:11] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[13:34:11] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[13:34:11] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[13:34:11] [Server thread/WARN]: 	at MythicMobs-5.7.1.jar//io.lumine.mythic.core.skills.conditions.CustomCondition.lambda$new$0(CustomCondition.java:33)
[13:34:11] [Server thread/WARN]: 	at MythicMobs-5.7.1.jar//io.lumine.mythic.bukkit.utils.Delegates$RunnableToSupplier.get(Delegates.java:121)
[13:34:11] [Server thread/WARN]: 	at MythicMobs-5.7.1.jar//io.lumine.mythic.bukkit.utils.promise.LuminePromise$SupplyRunnable.run(LuminePromise.java:654)
[13:34:11] [Server thread/WARN]: 	at MythicMobs-5.7.1.jar//io.lumine.mythic.bukkit.utils.tasks.LumineExecutors$SchedulerWrappedRunnable.run(LumineExecutors.java:70)
[13:34:11] [Server thread/WARN]: 	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86)
[13:34:11] [Server thread/WARN]: 	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475)
[13:34:11] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226)
[13:34:11] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[13:34:11] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1570)
[13:34:11] [Server thread/WARN]: Caused by: java.lang.IllegalArgumentException: No enum constant io.lumine.mythic.core.skills.conditions.ConditionAction.TRUE
[13:34:11] [Server thread/WARN]: 	at java.base/java.lang.Enum.valueOf(Enum.java:293)
[13:34:11] [Server thread/WARN]: 	at MythicMobs-5.7.1.jar//io.lumine.mythic.core.skills.conditions.ConditionAction.valueOf(ConditionAction.java:5)
[13:34:11] [Server thread/WARN]: 	at MythicMobsExtension-MC-1.21.1-v1.757-SNAPSHOT.jar//com.gmail.berndivader.mythicmobsext.conditions.AbstractCustomCondition.<init>(AbstractCustomCondition.java:22)
[13:34:11] [Server thread/WARN]: 	at MythicMobsExtension-MC-1.21.1-v1.757-SNAPSHOT.jar//com.gmail.berndivader.mythicmobsext.conditions.VerticalDistanceCondition.<init>(VerticalDistanceCondition.java:15)
[13:34:11] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
[13:34:11] [Server thread/WARN]: 	... 20 more
```

Paper 1.21.1 # 52
MythicMobs 5.7.1
MME MythicMobsExtension-MC-1.21.1-v1.757-SNAPSHOT

**Comment by LadyHaley** [comment]
[latest.log](https://github.com/user-attachments/files/16823335/latest.log)

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by LadyHaley** [comment]
The above comment is a compromised account that is being used to spread viruses, dont download it at all

**Comment by chrisgdt** [comment]
Can you try with MythicMobs 5.7.2 ?

**Comment by chrisgdt** [comment]
It seems that you are using a "conditionaction" set as "true" or "false". These are aliases for respectively "REQUIRED" and "CANCEL", but somehow alias doesn't work with MME.

Either you can change this to the real name and not alias, or you can get the MME fixed jar (discord or I will try to upload a tag on GitHub).

**Comment by LadyHaley** [comment]
The jar fixed this issue :) Thank you
